export enum CustomExceptions {
  USER_NOT_FOUND = 'User not found.',
  VERIFY_CODE_INCORRECT = 'VERIFY_CODE_INCORRECT',
  SAME_PASSWORDS = 'SAME_PASSWORDS',
  INCORRECT_PASSWORD = 'INCORRECT_PASSWORD',
}
